### ISSUE TITLE
Scopes and html tags inside the datatable

### ISSUE THREAD

**Issue by luis77** [ajahongir/ajax-datatables-rails-v-0-4-0-how-to#2]
Hi, how are you? THANK YOU the gem is amazing, I've been testing it. I only have a couple of doubts:
1) Is it possible to put an id to the <tr> of each record in the table with the id of the record? Something like this:  `<tr id="clasruta_<%= clasruta.id %>">`

2) Is it possible to apply scopes or querys to the table? If that's the way to do it?

3) Is it possible to place a button with an id inside the datatable? something like this:
`<button type="button" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#myupdateclasruta_<%= clasruta.id %>">
          Edit
        </button>`

**Comment by ajahongir** [comment]
Hey. thanks :+1: 
1. I think you need this one - https://datatables.net/reference/option/rowId
2. sure in your datatable:
```ruby
  def get_raw_records
    if params[:active]
      City.active
    else
      City.all
    end
  end
```
3. on render callback you can add your custom content in to a cell  https://datatables.net/reference/option/columns.render

**Comment by ajahongir** [comment]
>THANK YOU the gem is amazing

push a star button if you like it)

**Comment by luis77** [comment]
@ajahongir But how can I pass parameters to the get_raw_records method? Like this:     `@products = Producto.without_discount(params[:id]).por_empresa(current_user.empresa_id)`

**Comment by luis77** [comment]
@ajahongir I see in the example the data of the registers are placed in the action "def columns", "def data" and in the columns of the file .coffe. How can I show custom content inside the cell? Because I need to do for example a conditional like this in each record:   
```

  <td>
    <% if cliente.Credito == true%>
      <input type="checkbox" disabled="true" checked="true">
    <%else%>
      <input type="checkbox" disabled="true" >
    <%end%>
  </td>
```

**Comment by ajahongir** [comment]
well, here is working example:
```coffeescript
          $('.datatable').DataTable
            ordering: false
            searching: false
            'ajax': '/profile/users.json'
            columns: [
                data: "created_at"
              ,
                data: "first_name"
              ,
                data: "last_name"
              ,
                data: "zipcode"
              ,
                data: "city"
              ,
                data: "package", render: (data) ->
                  data.title
              ,
                data: "status"
              ,
                data: null, render: (data) ->
                  if data.align == 'non_aligned'
                    '<div class="btn-group client-align" data-id="'+data.id+'">
                      <a class="btn btn-sm btn-primary" data-align="left" role="button">Left</a>
                      <a class="btn btn-sm btn-info" data-align="right" role="button">Right</a>
                    </div>'
                  else
                    ''
            ]
```

**Comment by ajahongir** [comment]
>on render callback you can add your custom content in to a cell https://datatables.net/reference/option/columns.render

**Comment by luis77** [comment]
@ajahongir It works but when I press the arrow on the <th> to organize data into the datatable, it shows me the following error: 
```
NoMethodError (undefined method `[]' for nil:NilClass):
  app/datatables/cliente_datatable.rb:17:in `data'
  app/controllers/clientes_controller.rb:16:in `block (2 levels) in index'
  app/controllers/clientes_controller.rb:12:in `index'
```
In this way place it in the .coffee file:
```

class App.Clientes extends App.Base

  index: ->
    $ ->
      $('#dataTable').dataTable
        ajax: clientes_path()
        columns: [
            data: "IdCli"
          ,
            data: null, render: (data) ->
              if data.Credito == true
                'text1'
              else
                'text2'
        ]
```

**Comment by ajahongir** [comment]
turn off sorting and searching for this column. you have to look dataTable options for info

**Comment by luis77** [comment]
@ajahongir  But this way it is not possible to do sorting or searching?
